version: 2

sphinx:
  configuration: ksenia_sandbox/doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
     # You can also specify other tool versions:
     # nodejs: "18"
     # rust: "1.64"

python:
  install:
    - method: pip
      path: sphinx
 
# Build PDF & ePub
#formats:
#  - htmlzip
#  - pdf
