version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

submodules:
  include: all
  recursive: true

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt

build:
  commands:
    - echo "Building multilingual documentation..."
    - cd ksenia-sandbox-eng && git checkout main
    - make -C ksenia-sandbox-eng/docs gettext
    - sphinx-build -b gettext docs/ docs/locale/ru/LC_MESSAGES/
    - sphinx-intl update -p docs/locale/ru/LC_MESSAGES/ -l en -d ksenia-sandbox-eng/docs/locale/